### ISSUE TITLE
Design terminals.

### ISSUE THREAD

**Issue by BrandonArmand** [BrandonArmand/Binari#12]
- [ ] Bug
- [ ] Clean up
- [ ] Question
- [ ] Enhancement
- [ ] Suggestion
- [x] Other
 
## What needs to be done.
Design the console and error screen to be more like an actual terminal.
 
<img width="1155" alt="Screen Shot 2020-01-23 at 9 50 32 PM" src="https://user-images.githubusercontent.com/27185256/73047381-673fbb80-3e2a-11ea-85c4-c2651f950711.png">

## Why
To look nice.

## How
Suggestions:
- Change font
- Add line numbers
- Add the current directory (fake it)
- possibly use another code editor that is disabled and just fill the code with the error/console logs.

**Comment by CptCrooked** [comment]
Hi @BrandonArmand, I would like to take this one.

**Comment by BrandonArmand** [comment]
@CptCrooked Feel free. I don't have any particular ideas in mind for it, so it's your call for how it looks. @gigirubi is our UI/UX Designer, so she will review it.

**Comment by CptCrooked** [comment]
As this is my first attempt at contributing to an open source project, I am unsure as to how you guys do things.

@gigirubi How do you normally review the design based side of things?
Please note that I am not sure if you have any specific themes or fonts in mind.
In the meantime, here is a plain old png:

![binari_logAndConsole](https://user-images.githubusercontent.com/46305395/75443961-29730d00-596b-11ea-8ad7-cf4dc6c16def.png)

@BrandonArmand I did do my best to dig into the code and see how I could get the line numbers in there. With the props not providing enough detail, I tried checking into the DOM and seeing if I could grab it that way but the issue with that tactic I have no way of determining the actual line that caused the error, as a variable/function that causes an error could be in multiple places.

Thank you to you guys for allowing me to try my hand at this. Really appreciate it.

**Comment by gigirubi** [comment]
@CptCrooked 
![image](https://user-images.githubusercontent.com/51354662/75476776-0b4be380-5950-11ea-82bd-f95fa92eb5e5.png)

Hey! Looks great and I love the idea that you have going on with the gradient bars and I think the inner console looks perfect. 

I would like to change up the gradient on the bars a bit so here is an image for reference and the hex codes and font are below! Thanks for helping out!
```
font-family: IBM Plex Mono;
font-style: normal;
font-weight: 300;
font-size: 24px;
line-height: 31px;

background: linear-gradient(179.45deg, #9EBDEC 6.17%, #5C78A2 93.84%);
background: linear-gradient(179.45deg, #CD0505 6.17%, #9F2828 93.84%);
```

**Comment by CptCrooked** [comment]
@gigirubi 
I had a few snags:

- The icon on the error console is only available on the pro version of font-awesome and therefore is not available.
- The icon on the console was styled differently to how font-awesome displayed it.

The only workaround I could think of was to create a couple of SVGs that look the same as the icons you wanted. Let me know what you think.

![binari_logAndConsole](https://user-images.githubusercontent.com/46305395/75517663-e87d0600-5a07-11ea-83f2-88c039fe5540.png)


@BrandonArmand Just so you are aware, the google fonts CDN is pulling in a lot of fonts already and the load time is slow. Is it ok for me to add this font?

Also, are you ok with me adding SVGs for the icons @gigirubi wanted. Both only add up to about 6KB. If you are ok with that shall I add them to the file structure as follows:

- src
  - assets
    - imgs (New Folder)
      - warning_icon.svg
      - console_icon.svg

Sorry if I am asking too many questions but I would rather check with you guys rather than adding stuff randomly and inadvertently breaking something in the app.

**Comment by BrandonArmand** [comment]
@CptCrooked Looks great man (: 

Add whatever you need to, and feel free to create a PR once you are done. I especially like what you did to the inner console as well.

**Comment by CptCrooked** [comment]
Sorry about the 1 million changes. my prettier has a bit of config to it.

**Comment by gigirubi** [comment]
@CptCrooked 
Looks great! Thanks for pulling them as SVG's and going that extra step that's awesome!

**Comment by BrandonArmand** [comment]
@CptCrooked its all good. If anything needs to be changed, ill change it. Just do a pull request on the repo and ill review it (:
