### ISSUE TITLE
Hide Jumbotron Text on Other Page

### ISSUE THREAD

**Issue by BrandonArmand** [BrandonArmand/Binari#9]
- [ ] Bug
- [ ] Clean up
- [ ] Question
- [x] Enhancement
- [ ] Suggestion
- [ ] Other
 
## What needs to be done.
Hide or change the header text when on a page other than the landing page.

<img width="702" alt="Screen Shot 2020-01-23 at 9 10 44 PM" src="https://user-images.githubusercontent.com/27185256/73045943-da463380-3e24-11ea-8a13-f71275c2b14b.png">

## Why
It seem pointless to have. It would be much more fitting to have it display the current page that the user is on with a small description of the page. The jumbotron can also be completely hidden similar to the Playground page.

## How
There are functions to check the current route, but if that doesn't work, the content section can be moved up to cover the jumbotron section.

**Comment by agustinmessina** [comment]
Hi, I came up with two posible solutions:

- **Rise about page with a negative margin top and hide jumbotron text**:
![image](https://user-images.githubusercontent.com/47067313/74165910-8c8f4080-4c04-11ea-8f77-f072a98ac3fe.png)

With this approach the length of the gray background stays the same as the others pages. The jumbotron text will be hidden for any page other than '/'. The problem is that if you add new pages you'll have to set the negative margin for those too.

- **Hide jumbotron text and reduce the size of the gray area**:
![image](https://user-images.githubusercontent.com/47067313/74166699-c6ad1200-4c05-11ea-81b6-d048ab15871c.png)

For any page other than '/' jumbotron text is hidden and size is reduced so the page is shown at the top. The advantage of this approach is that you don't have to configure new pages to adapt to jumbotron, it will always be reduced and text hidden. But if I reduce the size of jumbotron background, the gray area will appear different from the playground page for example. In the long run I think is more efective to reduce jumbotron size than editing all new pages with negative margin.

**Comment by BrandonArmand** [comment]
@agustinmessina I'm pretty sure we will need to go for the negative margin, which isn't a big deal, so if you agree that this is the better solution, you are welcome to do a pull request to close the issue (:
